name: Push
on:
  push:
    branches:
      - master
jobs:
  authors:
    name: Check authors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Check if authors file changed
        id: authors-changed
        uses: tj-actions/changed-files@v35
        with:
          files: |
            authors.json
      - name: Sync authors
        if: steps.authors-changed.outputs.any_changed == 'true'
        run: |
          chmod +x ./sync.sh
          ./sync.sh authors
        shell: bash
  channels:
    name: Check channels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Check if channels file changed
        id: channels-changed
        uses: tj-actions/changed-files@v35
        with:
          files: |
            channels.json
      - name: Sync channels
        if: steps.channels-changed.outputs.any_changed == 'true'
        run: |
          chmod +x ./sync.sh
          ./sync.sh channels
        shell: bash
  podcasts:
    name: Check podcasts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Check if podcasts file changed
        id: podcasts-changed
        uses: tj-actions/changed-files@v35
        with:
          files: |
            podcasts.json
      - name: Sync podcasts
        if: steps.podcasts-changed.outputs.any_changed == 'true'
        run: |
          chmod +x ./sync.sh
          ./sync.sh podcasts
        shell: bash
  streamers:
    name: Check streamers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Check if streamers file changed
        id: streamers-changed
        uses: tj-actions/changed-files@v35
        with:
          files: |
            streamers.json
      - name: Sync streamers
        if: steps.streamers-changed.outputs.any_changed == 'true'
        run: |
          chmod +x ./sync.sh
          ./sync.sh streamers
        shell: bash
