name: Push
on:
  push:
    branches:
      - master
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Check if authors file changed
        id: authors-changed
        uses: tj-actions/changed-files@v35
        with:
          files: |
            authors.json
      - name: Run step if any file(s) in the docs folder change
        if: steps.authors-changed.outputs.any_changed == 'true'
        run: |
          chmod +x "${GITHUB_WORKSPACE}/../sync.sh"
          "${GITHUB_WORKSPACE}/../sync.sh authors"
#      - name: Build & Deploy
#        run: |
#          chmod +x "${GITHUB_WORKSPACE}/sync.sh" "${GITHUB_WORKSPACE}/sync.sh"
